baseURL = "https://acrisprstory.com/"
languageCode = "en-us"
title = "EVA - a CRISPR story"
disableKinds = ["taxonomy", "taxonomyTerm"]
canonifyURLS = true

[Params]
  tagline = "EVA - a CRISPR story"
  author = "Puneet Bharill"
  description = "A short film about CRISPR technology and the ethical, moral and legal implications, its use may have on humans."
  logoBig = "/images/eva-poster.jpg"
  logoSmall = "/images/eva-logo.png"
  favicon = "favicon.ico"
  opengraphImage = "/images/eva-poster.jpg"
  email = ""
  googleTagManager = ""
  customCSS = false

[[menu.main]]
  name = "Festivals"
  url  = "/festivals"
  weight = 1
[[menu.main]]
  name = "Team"
  url  = "/team"
  weight = 2
[[menu.main]]
  name = "Stills"
  url  = "/stills"
  weight = 3
[[menu.main]]
  name = "Support us"
  url  = "/#contact"
  weight = 5

